### PR TITLE
App Crash in SubmitDataHandler

### LINKED ISSUE #174: App Crash in SubmitDataHandler
```java
Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1844)
       at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1884)
       at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:329)
       at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:294)
       at androidx.fragment.app.DialogFragment.show(DialogFragment.java:260)
       at com.onaio.steps.handler.actions.SubmitDataHandler.displayUploadResult(SubmitDataHandler.java:177)
       at com.onaio.steps.handler.actions.SubmitDataHandler$1.onFileUploaded(SubmitDataHandler.java:101)
       at com.onaio.steps.helper.UploadFileTask.isDone(UploadFileTask.java:119)
       at com.onaio.steps.helper.UploadFileTask$1.onResponse(UploadFileTask.java:99)
       at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0$DefaultCallAdapterFactory$ExecutorCallbackCall$1(DefaultCallAdapterFactory.java:89)
       at retrofit2.-$$Lambda$DefaultCallAdapterFactory$ExecutorCallbackCall$1$hVGjmafRi6VitDIrPNdoFizVAdk.run(:6)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:233)
       at android.app.ActivityThread.main(ActivityThread.java:8010)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

### PR DESCRIPTION
**Pull request by owais-vd**
close #174

### CODE REVIEW

File: src/main/java/com/onaio/steps/handler/actions/SubmitDataHandler.java [hunk 1]
```diff
@@ -173,7 +174,13 @@ public void enable() {
...
 
     public void displayUploadResult(List<UploadResult> uploadResults) {
-        HouseholdUploadResultDialog householdUploadResultDialog = new HouseholdUploadResultDialog(uploadResults);
-        householdUploadResultDialog.show(activity.getSupportFragmentManager(), HouseholdUploadResultDialog.class.getSimpleName());
+        try {
+            HouseholdUploadResultDialog householdUploadResultDialog = new HouseholdUploadResultDialog(uploadResults);
+            FragmentTransaction fragmentTransaction = activity.getSupportFragmentManager().beginTransaction();
+            fragmentTransaction.add(householdUploadResultDialog, HouseholdUploadResultDialog.class.getSimpleName());
+            fragmentTransaction.commitAllowingStateLoss();
+        } catch (Exception ex) {
```
Comment (ekigamba) [inline src/main/java/com/onaio/steps/handler/actions/SubmitDataHandler.java:182]: Remove the unspecified `try { } catch (Exception)`.

Why is this error happening?

**Review by ekigamba — CHANGES_REQUESTED** [review]

File: src/main/java/com/onaio/steps/handler/actions/SubmitDataHandler.java (hunk 1 above)
Comment (owais-vd) [reply src/main/java/com/onaio/steps/handler/actions/SubmitDataHandler.java:182]: previously, having a problem with the `commit()` method if we destroy the activity before showing the dialog fragment. The issue was fixed when i replace the `commit` method with `commitAllowingStateLoss`. Code updated with and try-catch now removed

Comment (ekigamba) [reply src/main/java/com/onaio/steps/handler/actions/SubmitDataHandler.java]: OK, from my understanding. This dialog is only shown once the upload is done. You are saying that you get a crash when the activity finishes before showing the dialog fragment, I don't understand if this is right.

On the other hand, I believe this error occurs if you try to show the dialog when the activity is either paused or finishing. Is there a better way to prevent showing the dialog if the activity is in either states?

**Review by hilpitome — APPROVED** [review]
