### PR TITLE
DatabaseHelper.java line 55 com.onaio.steps.helper.DatabaseHelper.onUpgrade

### LINKED ISSUE #167: DatabaseHelper.java line 55 com.onaio.steps.helper.DatabaseHelper.onUpgrade
Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{com.onaio.steps/com.onaio.steps.activities.HouseholdListActivity}: android.database.sqlite.SQLiteException: duplicate column name: Server_Status (code 1 SQLITE_ERROR[1]): , while compiling: ALTER TABLE household ADD COLUMN Server_Status TEXT default 'NOT_SENT'

```java
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.onaio.steps/com.onaio.steps.activities.HouseholdListActivity}: android.database.sqlite.SQLiteException: duplicate column name: Server_Status (code 1 SQLITE_ERROR[1]): , while compiling: ALTER TABLE household ADD COLUMN Server_Status TEXT default 'NOT_SENT'
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3846)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4022)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

### PR DESCRIPTION
**Pull request by owais-vd**
close #167

### CODE REVIEW

File: src/main/java/com/onaio/steps/helper/DatabaseHelper.java [hunk 1]
```diff
@@ -106,4 +106,26 @@ public void close(){
...
+        Cursor cursor = db.rawQuery("PRAGMA table_info(" + tableName + ")", null);
+        if(cursor.moveToFirst()) {
+            do {
+                String currentColumn = cursor.getString(1);
+                if (currentColumn.equals(columnName)) {
+                    isExist = true;
+                    break;
+                }
+            } while (cursor.moveToNext());
+        }
```
Comment (ekigamba) [inline src/main/java/com/onaio/steps/helper/DatabaseHelper.java:127]: Close the cursor here

**Review by ekigamba — CHANGES_REQUESTED** [review]

File: src/main/java/com/onaio/steps/helper/DatabaseHelper.java (hunk 1 above)
Comment (owais-vd) [reply src/main/java/com/onaio/steps/helper/DatabaseHelper.java:127]: done

**Review by ekigamba — APPROVED** [review]
