### PR TITLE
App crash on Uploading Data

### LINKED ISSUE #173: App crash on Uploading Data
```java
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
       at com.onaio.steps.helper.UploadFileTask.prepareForUpload(UploadFileTask.java:69)
       at com.onaio.steps.handler.actions.ExportHandler.lambda$open$0$ExportHandler(ExportHandler.java:97)
       at com.onaio.steps.handler.actions.-$$Lambda$ExportHandler$aQFxG4jALkyJ7eVGYynziELAnFQ.onClick(:2)
```

### PR DESCRIPTION
**Pull request by owais-vd**
close #173

### CODE REVIEW

File: src/test/java/com/onaio/steps/helper/UploadFileTaskTest.java [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+
+    @Test
+    public void testIsAllFieldValidShouldValidateAllGivenFields() {
+
+        // verify valid fields
+        assertTrue(uploadFileTask.isAllFieldValid("user_id"));
+        assertTrue(uploadFileTask.isAllFieldValid("user_id", "user_password"));
+
+        // verify invalid fields
+        assertFalse(uploadFileTask.isAllFieldValid((String) null));
```
Comment (ekigamba) [inline src/test/java/com/onaio/steps/helper/UploadFileTaskTest.java:34]: Split these different assertions into multiple tests. Otherwise, nice work :+1:

**Review by ekigamba — CHANGES_REQUESTED** [review]

File: src/test/java/com/onaio/steps/helper/UploadFileTaskTest.java (hunk 1 above)
Comment (owais-vd) [reply src/test/java/com/onaio/steps/helper/UploadFileTaskTest.java:38]: done

**Review by ekigamba — APPROVED** [review]
